id: opecha:P008059
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG871
  title: ཝིཏནེསས་ཏོ་ཏིབེཏའས་ཧིསྟོརཡ
  volume:
    7b566f8e3c0a4c358fafc0570482c338:
      image_group_id: I1KG1006
      title: Volume 1 of witness to tibet's history
      volume_number: 1
      total_pages: 158
  author: ''
ebook_metadata:
  title: ཝིཏནེསས་ཏོ་ཏིབེཏའས་ཧིསྟོརཡ
  author: ''
  sku: P008059
  cover: cover.jpg
  layers:
  - pagination
