id: P008059
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG871
  title: ཝིཏནེསས་ཏོ་ཏིབེཏའས་ཧིསྟོརཡ
  author: ''
  volumes:
    8bd992355b184ec4a6decfe8807ca077:
      image_group_id: I1KG1006
      title: ''
      volume_number: 1
      total_pages: 158
ebook_metadata:
  title: ཝིཏནེསས་ཏོ་ཏིབེཏའས་ཧིསྟོརཡ
  author: ''
  sku: P008059
  cover: cover.jpg
  layers:
  - pagination
