id: P008059
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG871
  title: ཝིཏནེསས་ཏོ་ཏིབེཏའས་ཧིསྟོརཡ
  author: ''
  volumes:
    7b566f8e3c0a4c358fafc0570482c338:
      image_group_id: I1KG1006
      title: Volume 1 of witness to tibet's history
      volume_number: 1
      total_pages: 158
      base_file: v001.txt
